# ベースイメージとして公式のGolangイメージを使用
FROM golang:latest

# 作業ディレクトリを設定
WORKDIR /app

# Go Modulesの使用を許可（必要な場合）
# ENV GO111MODULE=on

# ローカルのモジュールキャッシュを最適化（必要な場合）
# COPY go.mod .
# COPY go.sum .
# RUN go mod download

# ソースコードをコンテナにコピー
COPY . .

# RUN go mod tidy

# # 依存関係をダウンロード
# RUN go mod download

# アプリケーションをビルド
RUN go build -o main

# アプリケーションを実行
CMD ["./main"]